version: "3.2"
services:
   php:
     build: './php/'
     networks:
       - backend
     volumes:
       - /mnt/nfsdata/a3/webapp/:/app/
   apache-webapp:
     depends_on:
       - php
     networks:
       #- frontend
       - backend
     ports:
       - '80:80'
     volumes:
       - /mnt/nfsdata/a3/webapp/:/usr/local/apache2/htdocs/
     build: './apache-webapp/'
networks:
#   frontend:
   backend:

